MODULES := mdd
mdd-objs := \
	mdd_acl.o \
	mdd_device.o \
	mdd_dir.o \
	mdd_lock.o \
	mdd_lproc.o \
	mdd_object.o \
	mdd_orphans.o \
	mdd_permission.o \
	mdd_trans.o
include /root/workspace_ych/FAST27/scaladfs-thread-model/lustre-sim-fifo/Rules
