MODULES := lnet_selftest

lnet_selftest-objs := console.o conrpc.o conctl.o framework.o timer.o rpc.o \
		      module.o ping_test.o brw_test.o

default: all

include /root/workspace_ych/FAST27/scaladfs-thread-model/lustre-sim-fifo/Rules
