MODULES := kkfilnd

kkfilnd-objs := \
	kfilnd.o \
	kfilnd_modparams.o \
	kfilnd_tn.o \
	kfilnd_ep.o \
	kfilnd_dev.o \
	kfilnd_dom.o \
	kfilnd_peer.o \
	kfilnd_cq.o \
	kfilnd_debugfs.o \

EXTRA_POST_CFLAGS += 

include /root/workspace_ych/FAST27/scaladfs-thread-model/lustre-sim-fifo/Rules
