MODULES := ksocklnd

ksocklnd-objs := \
	socklnd.o \
	socklnd_cb.o \
	socklnd_lib.o \
	socklnd_modparams.o \
	socklnd_proto.o

include /root/workspace_ych/FAST27/scaladfs-thread-model/lustre-sim-fifo/Rules
