MODULES := lfsck
lfsck-objs := lfsck_lib.o lfsck_engine.o lfsck_bookmark.o lfsck_namespace.o
lfsck-objs += lfsck_layout.o lfsck_striped_dir.o

include /root/workspace_ych/FAST27/scaladfs-thread-model/lustre-sim-fifo/Rules
