# SPDX-License-Identifier: GPL-2.0

#
# This file is part of Lustre, http://www.lustre.org/
#
# Makefile.in
#
# Template to generate top-level Makefile
#

obj-m += / libcfs/ lnet/
obj-m += lustre/

include /root/workspace_ych/FAST27/sim-fifo-v3/lustre-sim-fifo/Rules
