obj-m += fid/
obj-m += obdclass/
obj-m += ptlrpc/
obj-m += ldlm/
obj-m += obdecho/
obj-m += mgc/
obj-m += ec/
obj-m += tests/kernel/

#obj-m += ost/ mgs/ mdt/ mdd/ ofd/ quota/ osp/ lod/ lfsck/ target/
obj-m += lov/ osc/ mdc/ lmv/ llite/ fld/
#obj-m += osd-ldiskfs/
#obj-m += osd-zfs/


include /root/workspace_ych/FAST27/scaladfs-thread-model/lustre-sim-fifo/Rules
